<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TasmiSharafSeeder extends Seeder
{
    public function run()
    {
        $mapelId = 9;

        // Pastikan kategoris ada
        $kategoriIds = $this->_ensureKategoris($mapelId);

        // Hapus kriteria lama untuk kategori 1 & 2
        $this->db->table('kriteria_penilaian')
            ->whereIn('kategori_id', [$kategoriIds[1], $kategoriIds[2]])
            ->delete();
        echo "  Kriteria lama untuk Jilid 1 & 2 dihapus.\n";

        // Insert checkbox items for Jilid 1
        $itemsJ1 = [
            'Defenisi Sharaf Secara Bahasa Dan Istilah',
            'Asal Kalimat Menurut Ulama Kufah Dan Bashrah',
            'Lagu Amtsilah Mukhtalifah Beserta Makna',
            'Defenisi Amtsilah Mukhtalifah Serta Contohnya',
            'Skema-Skema Fi\'il',
            'Defenisi Fi\'il Secara Bahasa Dan Istilah',
            'Pembagian Fi\'il Dipandang Dari Zamannya',
            'Defenisi Fi\'il Madhi Serta Contohnya',
            'Tanda Fi\'il Madhi',
            'Defenisi Fi\'il Mudhari\' Serta Contohnya',
            'Tanda Fi\'il Mudhari\'',
            'Defenisi Fi\'il Amar Serta Contohnya',
            'Tanda Fi\'il Amar',
            'Pembagian Fi\'il Dipandang Dari Segi Faedah/ Bina',
            'Lagu Macam-Macam Faedah/ Bina Fi\'il',
            'Defenisi Masing-Masing Faedah/Bina Fi\'il Serta Contohnya',
            'Pembagian Fi\'il Dipandang Dari Segi Keadaan Hurufnya',
            'Defenisi Fi\'il Salim Serta Contohnya',
            'Defenisi Fi\'il Ghairu Salim',
            'Pembagian Fi\'il Ghairu Salim',
            'Defenisi Mu\'tal',
            'Lagu Huruf-Huruf `Ilat',
            'Pembagian Fi\'il Mu\'tal Serta Nama Lainnya',
            'Defenisi Mu\'tal Fa\' (Mitsal) Serta Contohnya',
            'Defenisi Mu\'tal \'Ain (Ajwaf) Serta Contohnya',
            'Defenisi Mu\'tal Lam (Naqis) Serta Contohnya',
            'Defenisi Mu\'tal \'Ain Dan Lam (Lafif Maqrun) Serta Contohnya',
            'Defenisi Mu\'tal Fa\' Dan Lam (Lafif Mafruq) Serta Contohnya',
            'Defenisi Mahmuz',
            'Pembagian Mahmuz',
            'Defenisi Mahmuz Fa\' Serta Contohnya',
            'Defenisi Mahmuz \'Ain Serta Contohnya',
            'Defenisi Mahmuz Lam Serta Contohnya',
            'Defenisi Tadh\'if',
            'Pembagian Tadh\'if',
            'Defenisi Tadh\'if Tsulasy Serta Contohnya',
            'Defenisi Tadh\'if Rubai\'i Serta Contohnya',
            'Pembagian Fi\'il Dipandang Dari Huruf Asalnya',
            'Lagu Cara Membuat Tasrif Isthilahi Dari Fi\'il Tsulasi Dan Ruba\'i',
            'Cara Membuat Masdar Mim Tsulasi Mujarrad',
            'Cara Membuat Masdar Mim Selain Tsulasi Mujarrad Beserta Keterangan',
            'Cara Membuat Isim Fail Tsulasi Mujarrad',
            'Cara Membuat Isim Fail Selain Tsulasi Mujarrad',
            'Cara Membuat Isim Maf\'ul Tsulasi Mujarrad',
            'Cara Membuat Isim Maf\'ul Selain Tsulasi Mujarrad Beserta Keterangan',
            'Cara Membuat Fi\'il Amar',
            'Cara Membuat Fi\'il Nahi',
            'Cara Membuat Isim Zaman/Makan Tsulasi Mujarrad Beserta Keterangan',
            'Cara Membuat Isim Zaman/Makan Selain Tsulasi Mujarrad Beserta Keterangan',
            'Cara Membuat Isim Alat Tsulasi Majarrad Beserta Keterangan',
            'Defenisi Fi\'il Tsulasy',
            'Pembagian Fi\'il Tsulasy',
            'Defenisi Fi\'il Tsulasy Mujarrad',
            'Wazan Mauzun Bab Tsulasy Mujarrad',
            'Tanda Dan Bina\' Tsulasy Mujarrad Bab 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mujarrad Bab 2',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mujarrad Bab 3',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mujarrad Bab 4',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mujarrad Bab 5',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mujarrad Bab 6',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Fi\'il Tsulasy Mazid',
            'Pembagian Fi\'il Tsulasy Mazid',
            'Defenisi Fi\'il Tsulasy Mazid 1',
            'Wazan Mauzun Bab Tsulasy Mazid 1',
            'Tanda Dan Bina\' Tsulasy Mazid 1 Bab 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 1 Bab 2',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 1 Bab 3',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Fi\'il Tsulasy Mazid 2',
            'Wazan Mauzun Bab Tsulasy Mazid 2',
            'Tanda Dan Bina\' Tsulasy Mazid 2 Bab 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 2 Bab 2',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 2 Bab 3',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 2 Bab 4',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 2 Bab 5',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Fi\'il Tsulasy Mazid 3',
            'Wazan Mauzun Bab Tsulasy Mazid 3',
            'Tanda Dan Bina\' Tsulasy Mazid 3 Bab 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 3 Bab 2',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 3 Bab 3',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Tsulasy Mazid 3 Bab 4',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Fi\'il Ruba\'i',
            'Pembagian Fi\'il Ruba\'i',
            'Defenisi Fi\'il Ruba\'i Mujarrad',
            'Wazan Mauzun Bab Ruba\'i Mujarrad',
            'Tanda Dan Bina\' Ruba\'i Mujarrad',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Fi\'il Ruba\'i Mazid',
            'Pembagian Fi\'il Ruba\'i Mazid',
            'Defenisi Fi\'il Ruba\'i Mazid 1',
            'Wazan Mauzun Bab Ruba\'i Mazid 1',
            'Tanda Dan Bina\' Ruba\'i Mazid 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Fi\'il Ruba\'i Mazid 2',
            'Wazan Mauzun Bab Ruba\'i Mazid 2',
            'Tanda Dan Bina\' Ruba\'i Mazid 2 Bab 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Ruba\'i Mazid 2 Bab 2',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Mulhaq دحرج',
            'Wazan Mauzun Bab Mulhaq دحرج',
            'Tanda Dan Bina\' Mulhaq دحرج Bab 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq دحرج Bab 2',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq دحرج Bab 3',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq دحرج Bab 4',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq دحرج Bab 5',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq دحرج Bab 6',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Mulhaq تدحرج',
            'Wazan Mauzun Bab Mulhaq تدحرج',
            'Tanda Dan Bina\' Mulhaq تدحرج Bab 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq تدحرج Bab 2',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq تدحرج Bab 3',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq تدحرج Bab 4',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq تدحرج Bab 5',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Defenisi Mulhaq احرنجم',
            'Wazan Mauzun Bab Mulhaq احرنجم',
            'Tanda Dan Bina\' Mulhaq احرنجم Bab 1',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Tanda Dan Bina\' Mulhaq احرنجم Bab 2',
            'Tashrif Ishtilahi Dan Tashrif Lughawi Masing-Masingnya',
            'Pembagian Fi\'il Dipandang Dari Pelakunya',
            'Defenisi Fi\'il Ma\'lum (Di Bina Bagi Fa\'il) Serta Contohnya',
            'Defenisi Fi\'il Majhul (Di Bina Bagi Maf\'ul) Serta Contohnya',
            'Cara Membuat Fi\'il Madhi Jadi Majhul (Di Bina Bagi Maf\'ul) Serta Contohnya',
            'Cara Membuat Fi\'il Mudhari\' Jadi Majhul (Di Bina Bagi Maf\'ul) Serta Contohnya',
        ];

        $kriteriaJ1 = [];
        foreach ($itemsJ1 as $item) {
            $kriteriaJ1[] = [
                'mapel_id'    => $mapelId,
                'kategori_id' => $kategoriIds[1],
                'nama'        => $item,
                'bobot'       => 100,
                'skala_max'   => 100,
                'input_type'  => 'checkbox',
            ];
        }
        $this->db->table('kriteria_penilaian')->insertBatch($kriteriaJ1);
        echo '  ' . count($kriteriaJ1) . " kriteria checkbox untuk Jilid 1.\n";

        // Insert checkbox items for Jilid 2
        $itemsJ2 = [
            'Keterangan masdhar mim, isim zaman, isim makan mitsal fa yang waw',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 4 Tsulasi Mazid dua',
            'Keterangan naqhis wawi Bab 4 Tsulasi Mazid dua',
            'Defenisi I\'lal',
            'Kaidah I\'lal',
            'Defenisi Qalab',
            'Kaidah Qalab beserta contohnya',
            'Defenisi Hazaf',
            'Kaidah Hazaf beserta contohnya',
            'Defenisi Naqal',
            'Kaidah Naqal beserta contohnya',
            'Defenisi Hazaf',
            'Kaidah Hazaf beserta contohnya',
            'Defenisi Naqal',
            'Kaidah Naqal beserta contohnya',
            'Defenisi Idgham dan pembagiannya',
            'Defenisi Idgham Wajib dan contohnya',
            'Defenisi Idgham Jaiz dan contohnya',
            'Defenisi Idgham Mumtani\'/terlarang dan contohnya',
            'Pembagian fi\'il ghairu salim',
            'Bab-bab fi\'il mitsal wawi (mu\'tal fa yang waw)',
            'Bab-bab fi\'il mitsal ya\'i (mu\'tal fa yang ya)',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Wawi Bab 2 Tsulasi Mujarrad',
            'Keterangan i\'lal Mitsal Wawi Bab 2 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Wawi Bab 3 Tsulasi Mujarrad',
            'Keterangan i\'lal Mitsal Wawi Bab 3 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Wawi Bab 4 Tsulasi Mujarrad',
            'Keterangan i\'lal Mitsal Wawi Bab 4 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Wawi Bab 5 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Wawi Bab 6 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan lughawi mitsal wawi bab 1 tsulasi mazid satu',
            'Keterangan mitsal wawi bab 1 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi mitsal wawi bab 2 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi mitsal wawi bab 3 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi mitsal wawi bab 2 tsulasi mazid dua',
            'Keterangan mitsal wawi bab 2 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi mitsal wawi bab 4 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi mitsal wawi bab 5 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi mitsal wawi bab 1 tsulasi mazid tiga',
            'Keterangan mitsal wawi bab 1 tsulasi mazid tiga',
            'Bab-bab fi\'il mitsal ya\'i (mu\'tal fa yang ya)',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Yai Bab 2 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Yai Bab 3 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Yai Bab 4 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Mitsal Yai Bab 5 Tsulasi Mujarrad',
            'Keterangan Mitsal Yai Bab 5 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan lughawi mitsal Yai bab 1 tsulasi mazid satu',
            'Keterangan mitsal Yai bab 1 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi mitsal Yai bab 2 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi mitsal Yai bab 3 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi mitsal Yai bab 2 tsulasi mazid dua',
            'Keterangan mitsal Yai bab 2 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi mitsal Yai bab 4 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi mitsal Yai bab 5 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi mitsal Yai bab 1 tsulasi mazid tiga',
            'Bab-bab ajwaf waw (mu\'tal \'ain yang waw)',
            'Bab-bab ajwaf yai (mu\'tal \'ain yang ya)',
            'Tashrif Isthilahy dan Tashrif Lughawi Ajwaf wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan Ajwaf wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan Fiil Madhi Ajwaf wawi Bab 1 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Ajwaf wawi Bab 4 Tsulasi Mujarrad',
            'Keterangan Ajwaf wawi Bab 4 Tsulasi Mujarrad',
            'Keterangan Fiil Madhi Ajwaf wawi Bab 4 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Ajwaf wawi Bab 5 Tsulasi Mujarrad',
            'Keterangan Ajwaf wawi Bab 5 Tsulasi Mujarrad',
            'Keterangan Fiil Madhi Ajwaf wawi Bab 5 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 1 tsulasi mazid satu',
            'Keterangan Ajwaf wawi bab 1 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 2 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 3 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 1 tsulasi mazid dua',
            'Keterangan Ajwaf wawi bab 1 tsulasi mazid dua',
            'Keterangan fiil madhi Ajwaf wawi bab 1 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 2 tsulasi mazid dua',
            'Keterangan Ajwaf wawi bab 2  tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 3 tsulasi mazid dua',
            'Keterangan Ajwaf wawi bab 3  tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 4 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 5 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf wawi bab 1 tsulasi mazid tiga',
            'Keterangan Ajwaf wawi bab 1  tsulasi mazid tiga',
            'Bab-bab ajwaf yai (mu\'tal \'ain yang ya)',
            'Tashrif Isthilahy dan Tashrif Lughawi Ajwaf Yai Bab 2 Tsulasi Mujarrad',
            'Keterangan Ajwaf Yai Bab 2 Tsulasi Mujarrad',
            'Keterangan fiil madhi Ajwaf Yai Bab 2 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi Ajwaf Yai Bab 4 Tsulasi Mujarrad',
            'Keterangan Ajwaf Yai Bab 4 Tsulasi Mujarrad',
            'Keterangan fiil madhi Ajwaf Yai Bab 4 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 1 tsulasi mazid satu',
            'Keterangan Ajwaf Yai bab 1 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 2 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 3 tsulasi mazid satu',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 1 tsulasi mazid dua',
            'Keterangan Ajwaf Yai bab 1 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 2 tsulasi mazid dua',
            'Keterangan Ajwaf Yai bab 2 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 3 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 4 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 5 tsulasi mazid dua',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 1 tsulasi mazid tiga',
            'Keterangan Ajwaf Yai bab 1 tsulasi mazid tiga',
            'Tashrif Isthilahy dan lughawi Ajwaf Yai bab 4 tsulasi mazid tiga',
            'Bab- bab mu\'tal lam yang waw ( naqish wawi)',
            'Bab- bab mu\'tal lam yang ya ( naqish yai)',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan naqhis wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan fiil madhi naqhis wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan fiil mudhari naqhis wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan masdar mim naqhis wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan isim fa\'il naqhis wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan fiil amar naqhis wawi Bab 1 Tsulasi Mujarrad',
            'Keterangan isim zaman dan makan naqhis wawi Bab 1 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 5 Tsulasi Mujarrad',
            'Keterangan naqhis wawi Bab 5 Tsulasi Mujarrad',
            'Keterangan fiil madhi naqhis wawi Bab 5 Tsulasi Mujarrad',
            'Keterangan fiil mudhari naqhis wawi Bab 5 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 1 Tsulasi Mazid satu',
            'Keterangan naqhis wawi Bab 1 Tsulasi Mazid satu',
            'Keterangan fiil madhi naqhis wawi Bab 1 Tsulasi Mazid satu',
            'Keterangan fiil mudhari naqhis wawi Bab 1 Tsulasi Mazid satu',
            'Keterangan isim fail naqhis wawi Bab 1 Tsulasi Mazid satu',
            'Keterangan isim maf\'ul  naqhis wawi Bab 1 Tsulasi Mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 2  Tsulasi Mazid satu',
            'Keterangan naqhis wawi Bab 2 Tsulasi Mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 3  Tsulasi Mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 1 Tsulasi Mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 5 Tsulasi Mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 1 Tsulasi Mazid tiga',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis wawi Bab 2 Tsulasi Mazid tiga',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 2 Tsulasi Mujarrad',
            'Keterangan naqhis yai Bab 2 Tsulasi Mujarrad',
            'Keterangan fiil mudhari\' naqhis yai Bab 2 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 4 Tsulasi Mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 1 Tsulasi Mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 2 Tsulasi Mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 3 Tsulasi Mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 1 Tsulasi Mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 2 Tsulasi Mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 4 Tsulasi Mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 5 Tsulasi Mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi naqhis yai Bab 1 Tsulasi Mazid tiga',
            'Bab-bab Mu\'tal fa dan lam (lafif mafruq)',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 2 tsulasi mujarrad',
            'Keterangan lafif mafruq bab 2 tsulasi mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 4 tsulasi mujarrad',
            'Keterangan lafif mafruq bab 4 tsulasi mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 1 tsulasi mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 2 tsulasi mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 3 tsulasi mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 2 tsulasi mazid dua',
            'Keterangan lafif mafruq bab 2 tsulasi mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 4 tsulasi mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 5 tsulasi mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif mafruq bab 1 tsulasi mazid tiga',
            'Bab-bab Mu\'tal \'ain dan lam (lafif maqrun)',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 2 tsulasi mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 4 tsulasi mujarrad',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 1 tsulasi mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 2 tsulasi mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 3 tsulasi mazid satu',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 2 tsulasi mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 4 tsulasi mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 5 tsulasi mazid dua',
            'Tashrif Isthilahy dan Tashrif Lughawi lafif maqrun bab 1 tsulasi mazid tiga',
        ];

        $kriteriaJ2 = [];
        foreach ($itemsJ2 as $item) {
            $kriteriaJ2[] = [
                'mapel_id'    => $mapelId,
                'kategori_id' => $kategoriIds[2],
                'nama'        => $item,
                'bobot'       => 100,
                'skala_max'   => 100,
                'input_type'  => 'checkbox',
            ];
        }
        $this->db->table('kriteria_penilaian')->insertBatch($kriteriaJ2);
        echo '  ' . count($kriteriaJ2) . " kriteria checkbox untuk Jilid 2.\n";

        echo "Selesai.\n";
    }

    private function _ensureKategoris(int $mapelId): array
    {
        $tblKategori = $this->db->table('kategori');
        $all = $tblKategori->where('mapel_id', $mapelId)->orderBy('urutan')->get()->getResultArray();

        $byUrutan = [];
        foreach ($all as $k) {
            $byUrutan[$k['urutan']] = $k;
        }

        $namaByUrutan = [1 => 'Jilid 1', 2 => 'Jilid 2', 3 => 'Nilai Ujian'];
        $kategoriIds = [];

        for ($u = 1; $u <= 3; $u++) {
            if (isset($byUrutan[$u])) {
                // Update nama
                $tblKategori->where('id', $byUrutan[$u]['id'])->update(['nama' => $namaByUrutan[$u]]);
                $kategoriIds[$u] = $byUrutan[$u]['id'];
                echo "  Kategori urutan $u: {$namaByUrutan[$u]} (id={$byUrutan[$u]['id']})\n";
            } else {
                $tblKategori->insert([
                    'mapel_id' => $mapelId,
                    'nama'     => $namaByUrutan[$u],
                    'urutan'   => $u,
                    'is_active' => 1,
                ]);
                $id = $this->db->insertID();
                $kategoriIds[$u] = $id;
                echo "  Kategori baru: {$namaByUrutan[$u]} (id=$id)\n";
            }
        }

        return $kategoriIds;
    }
}
