<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TasmiItemSeeder extends Seeder
{
    public function run()
    {
        // Pastikan Kategori 2-4 Tasmi' sudah ada
        $existing = $this->db->table('kategori')
            ->where('mapel_id', 1)
            ->orderBy('urutan')
            ->get()
            ->getResultArray();

        $knownUrutan = array_column($existing, 'urutan');
        $newKategori = [];
        for ($u = 2; $u <= 4; $u++) {
            if (!in_array($u, $knownUrutan)) {
                $newKategori[] = ['mapel_id' => 1, 'nama' => "Tasmi' Kategori $u", 'urutan' => $u, 'is_active' => 1];
            }
        }
        if (!empty($newKategori)) {
            $this->db->table('kategori')->insertBatch($newKategori);
        }

        // Ambil ulang semua kategori Tasmi' untuk mapping
        $kategoris = $this->db->table('kategori')
            ->where('mapel_id', 1)
            ->orderBy('urutan')
            ->get()
            ->getResultArray();

        $kategoriMap = [];
        foreach ($kategoris as $k) {
            $kategoriMap[$k['urutan']] = $k['id'];
        }

        // Nonaktifkan kriteria Tasmi' lama (Kelancaran, Hafalan, Makhraj)
        $this->db->table('kriteria_penilaian')
            ->where('mapel_id', 1)
            ->whereNotIn('input_type', ['checkbox'])
            ->update(['is_active' => 0]);

        $data = [];

        // ===== KATEGORI 1 (urutan=1) =====
        $k1 = $kategoriMap[1] ?? null;
        $itemsJ1 = [
            'Rukun – Rukun Kalam',
            'Dalil Kalam',
            'Pembagian Kalimat',
            'Dalil Pembagian Kalimat',
            'Lagu Rukun Kalam dan Kalimat',
            'Defenisi Isim',
            'Tanda Isim',
            'Dalil Tanda Isim',
            'Dalil Huruf – Huruf Jer',
            'Defenisi Fi\'il',
            'Tanda Fi\'il',
            'Dalil Tanda Fi\'il',
            'Defenisi Huruf',
            'Dalil Huruf',
            'Skema atau Kaidah Isim',
            'Defenisi Mu\'rab',
            'Defenisi Mabni',
            'Keterangan tentang \'Amil',
            'Dalil Isim Mabni dan Mu\'rab',
            'Lagu tentang Mu\'rab dan Mabni',
            'Macam – Macam Isim Mu\'rab',
            'Macam – Macam Isim Mabni',
            'Macam – Macam Fi\'il Mu\'rab',
            'Macam – Macam Fi\'il Mabni',
            'Dalil Fi\'il Mu\'rab dan Mabni',
            'Dalil Huruf itu Mabni',
            'Pembagian I\'rab',
            'Tanda Asli I\'rab',
            'Dalil Tanda Asli I\'rab',
            'I\'rab untuk Isim',
            'I\'rab untuk Fi\'il',
            'Dalil I\'rab untuk Isim dan Fi\'il',
            'Defenisi Isim Mufrad',
            'Tanda I\'rab Isim Mufrad',
            'Dalil Tanda I\'rab Isim Mufrad',
            'Defenisi Isim Tasniyah',
            'Tanda I\'rab Isim Tasniyah',
            'Dalil Tanda I\'rab Isim Tasniyah',
            'Defenisi Jama\' Muzakkar Salim',
            'Tanda I\'rab Jama\' Muzakkar Salim',
            'Dalil Tanda I\'rab Jama\' Muzakkar Salim',
            'Dalil Perbedaan Isim Tasniyah dan Jama\' Muzakkar Salim Ketika Nashab dan Jer',
            'Defenisi Jama\' Muannats Salim',
            'Tanda I\'rab Jama\' Muannats Salim',
            'Dalil Tanda I\'rab Jama\' Muannats Salim',
            'Lagu Tanda – Tanda Perempuan',
            'Defenisi Jama\' Taksir',
            'Tanda I\'rab Jama\' Taksir',
            'Pembagian Jama\' Taksir',
            'Keterangan Jama\' Qillah',
            'Keterangan Jama\' Katsrah',
            'Wazan Jama\' Qillah',
            'Wazan Jama\' Katsrah',
            'Dalil Wazan Jama\' Taksir Qillah',
            'Dalil Tanda I\'rab Jama\' Taksir',
            'Asmaul Khamsah',
            'Tanda I\'rab Asmaul Khamsah',
            'Dalil Tanda I\'rab Asmaul Khamsah',
            'Lagu Arti Isim – Isim Yang Lima',
            'Keterangan Asmaul Khamsah',
            'Dalil Syarat Asmaul Khamsah',
            'Lagu Macam – Macam Illat',
            'Lagu Wazan – Wazan Isim Ghairu Munsharif',
            'Defenisi Isim Ghairu Munsharif',
            'Tanda I\'rab Isim Ghairu Munsharif',
            'Keterangan Isim Ghairu Munsharif',
            'Dalil Tanda I\'rab Isim Ghairu Munsharif',
            'Defenisi Isim Maqshur',
            'Tanda I\'rab Isim Maqshur',
            'Dalil Tanda I\'rab Isim Maqshur',
            'Defenisi Isim Manqush',
            'Tanda I\'rab Isim Manqush',
            'Dalil Tanda I\'rab Isim Manqush',
            'Defenisi Isim yang Mudhof Kepada Ya\' Mutakallim',
            'Tanda I\'rab Isim Yang Mudhof Kepada Ya\' Mutakallim',
            'Dalil Tanda I\'rab Isim Yang Mudhof Kepada Ya\' Mutakallim',
            'Lagu Tanda I\'rab Isim Mu\'rab',
        ];
        foreach ($itemsJ1 as $i => $nama) {
            $data[] = [
                'mapel_id' => 1,
                'kategori_id' => $k1,
                'nama' => $nama,
                'bobot' => 0,
                'skala_max' => 0,
                'input_type' => 'checkbox',
                'is_active' => 1,
            ];
        }

        // ===== KATEGORI 2 (urutan=2) =====
        $k2 = $kategoriMap[2] ?? null;
        $itemsJ2 = [
            'Defenisi Isim Nakirah',
            'Dalil Isim Nakirah',
            'Defenisi Isim Ma\'rifah',
            'Lagu Isim Ma\'rifah',
            'Isim Ma\'rifah yang pertama beserta contohnya',
            'Isim Ma\'rifah yang kedua beserta contohnya',
            'Pembagian Isim \'Alam beserta defenisinya',
            'Defenisi Isim Dhomir',
            'Dalil bahwa dhomir menunjukkan ghoib, ghoibah, mukhatab, mukhatabah, dan mutakallim',
            'Pembagian Dhomir',
            'Defenisi Dhomir Muttashil',
            'Defenisi Dhomir Munfashil',
            'Dalil bahwa dhomir itu Muttashil dan Munfashil',
            'I\'rab untuk Dhomir Muttashil',
            'Dhomir Muttashil Rafa\'',
            'Dhomir Muttashil Nashab',
            'Dhomir Muttashil Jer',
            'I\'rab untuk Dhomir Munfashil',
            'Dhomir Munfashil Rafa\'',
            'Dhomir Munfashil Nashab',
            'Ciri – ciri Dhomir Muttashil Mahal Nashab dan Jer',
            'Keterangan huruf Ha\' pada Dhomir Muttashil',
            'Keterangan huruf Mim pada Dhomir Jama\'',
            'Keterangan tentang Dhomir Ya\' Mutakallim',
            'Keterangan tentang Waqi\' dari Dhomir نا atau نحن',
            'Lagu tentang Isim Maushul',
            'Defenisi Isim Maushul',
            'Isim Maushul yang \'Am',
            'Isim Maushul yang Khas Muzakkar',
            'Isim Maushul yang Khas Muannats',
            'Defenisi Shillah',
            'Defenisi \'Aid',
            'Macam – macam Shillah',
            'Keterangan Shillah',
            'Dalil Shillah dan \'Aid',
            'Lagu Isim Isyarah',
            'Defenisi Isim Isyarah',
            'Isim Isyarah untuk Musyar Ilaih Muzakkar yang dekat',
            'Isim Isyarah untuk Musyar Ilaih Muannats yang dekat',
            'Isim Isyarah untuk Musyar Ilaih Muzakkar yang jauh',
            'Isim Isyarah untuk Musyar Ilaih Muannats yang jauh',
            'Isim Isyarah untuk tempat yang dekat',
            'Isim Isyarah untuk tempat yang jauh',
            'Rumus Isim Isyarah',
            'Dalil Mahal I\'rab Musyar Ilaih',
            'Defenisi Idhofat',
            'Keterangan I\'rab Mudhof',
            'Dalil Syarat Mudhof',
            'Keterangan I\'rab Mudhofun Ilaih',
            'Dalil I\'rab Mudhofun Ilaih',
            'Lagu kalimat yang selalu mudhof',
            'Defenisi Muzakkar',
            'Lagu tanda – tanda Perempuan',
            'Defenisi Muannats',
            'Dalil tanda – tanda muannats',
            'Cara menentukan lafaz muaanats',
            'Lagu isim Adad',
            'Defenisi Isim Adad',
            'Macam – macam Isim Adad',
            'Defenisi Adad Mufrad',
            'Keterangan kata setelah Adad Mufrad',
            'Defenisi Adad Murakkab',
            'Keterangan mengenai Adad Murakkab',
            'Keterangan mengenai Adad Murakkab wazan فاعل',
            'Dalil Adad Murakkab selalu mabni',
            'Defenisi Adad Athof',
            'Lagu Jamid dan Musytaq',
            'Defenisi Isim Jamid',
            'Macam – macam Isim Jamid',
            'Defenisi Isim Musytaq',
            'Macam –macam Isim Musytaq',
            'Lagu wazan – wazan isim Mustaq',
            'Wazan – wazan mashdar ghairu mim selain tsulasy',
            'Defenisi mashdar mim atau mashdar mimi',
            'Wazan – wazan mashdar Mim',
            'Defenisi Isim Fail',
            'Wazan – wazan isim Fail',
            'Dalil Isim Fail dari Fi\'il Madhi 3 huruf ikut wazan فاعل',
            'Cara membuat Isim Fail dari Fi\'il Madhi 4, 5, dan 6 huruf',
            'Dalil Cara membuat Isim Fail dari Fi\'il Madhi 4, 5, dan 6 huruf',
            'Defenisi Isim Maf\'ul',
            'Wazan – wazan Isim Maf\'ul',
            'Qaidah cara membuat isim Maf\'ul dari Fi\'il Madhi lebih 3 huruf',
            'Dalil qaidah cara membuat isim Maf\'ul dari Fi\'il Madhi lebih 3 huruf',
            'Keterangan wazan lain Isim Maf\'ul',
            'Dalil Isim Maf\'ul dari Fi\'il Madhi 3 huruf ikut wazan مفعول',
            'Defenisi Isim Alat',
            'Wazan – wazan Isim Alat',
            'Defenisi Isim Zaman',
            'Defenisi Isim Makan',
            'Rumus Isim Zaman dan Isim Makan',
            'Defenisi Isim Tashghir',
            'Fungsi Isim Tashghir',
            'Wazan – wazan Isim Tashghir',
            'Dalil Shigat Isim Tashgir',
            'Defenisi Isim Tafdhil',
            'Wazan Isim Tafdhil',
            'Dalil Isim Tafdhil',
            'Keterangan Isim Tafdhil',
            'Defenisi Isim Nasab',
            'Cara membuat Isim Nasab',
            'Dalil Isim Nasab',
            'Lagu Wazan – Wazan Shigat Mubalaghah',
            'Defenisi Shigat Mubalaghah',
            'Wazan – wazan Shighat Mubalaghah',
            'Dalil Wazan Shighat Mubalaghah',
        ];
        foreach ($itemsJ2 as $i => $nama) {
            $data[] = [
                'mapel_id' => 1,
                'kategori_id' => $k2,
                'nama' => $nama,
                'bobot' => 0,
                'skala_max' => 0,
                'input_type' => 'checkbox',
                'is_active' => 1,
            ];
        }

        // ===== KATEGORI 3 (urutan=3) =====
        $k3 = $kategoriMap[3] ?? null;
        $itemsJ3 = [
            'Defenisi Fi\'il',
            'Skema/ kaidah Fi\'il',
            'Defenisi Fi\'il Madhi',
            'Tanda-tanda fi\'il madhi',
            'Mabni Fi\'il Madhi dan contoh',
            'Dalil fi\'il madhi mabni fathah',
            'Dalil fi\'il madhi mabni Dhammah dan mabni sukun',
            'Bentuk Mabninya Fi\'il Madhi',
            'Defenisi fi\'il mujarrad',
            'Defenisi fi\'l mazid',
            'Wazan-wazan fi\'il madhi mujarrad',
            'Wazan-wazan fi\'il madhi mazid I',
            'Wazan-wazan fi\'il madhi mazid II',
            'Wazan-wazan fi\'il madhi mazid III',
            'Defenisi Fi\'il Mudhari\'',
            'Tanda-tanda Fi\'il Mudhari\'',
            'Lagu fi\'il mudhari\'',
            'Dalil huruf mudhara\'ah',
            'Pembagian Fi\'il Mudhari\'',
            'Defenisi Fi\'il Mudhari\' shohih akhir dan contoh',
            'Defenisi Fi\'il Mudhari\' mu\'tal akhir dan contoh',
            'Defenisi Af\'alul Khamsah dan contoh',
            'Lagu Af\'alul Khamsah',
            'I\'rab Fi\'il Mudhari\' shohih akhir',
            'Keterangan fi\'il mudhari\' i\'rab Rafa\'',
            'Dalil fi\'il mudhari\' i\'rab Rafa\'',
            'I\'rab Fi\'il Mudhari\' Mu\'tal alif',
            'I\'rab Fi\'il Mudhari\' Mu\'tal waw',
            'I\'rab Fi\'il Mudhari\' Mu\'tal ya',
            'Dalil Fi\'il Mudhari\' Mu\'tal akhir',
            'I\'rab Af\'alul Khamsah',
            'Dalil Af\'alul Khamsah I\'rab Rafa\'',
            'Dalil Af\'alul Khamsah I\'rab Nasab',
            'Dalil Af\'alul Khamsah I\'rab Jazam',
            'Wazan-wazan fi\'il Mudhari\' mujarrad/ sulasi',
            'Wazan-wazan fi\'il Mudhari\' mazid I/ ruba\'i',
            'Wazan-wazan fi\'il Mudhari\' mazid II/ khumasi',
            'Wazan-wazan fi\'il Mudhari\' mazid III/ sudasi',
            'Keterangan bacaan Huruf mudhara\'ah',
            'Dalil bacaan Huruf mudhara\'ah',
            'Amil-amil yang masuk pada fi\'il mudhari\'',
            'Amil-amil Nashab dan pembagiannya (menasabkan dengan sendiri dan menyimpan أن)',
            'Lagu amil nashab',
            'Dalil Amil-amil Nashab',
            'Keterangan lam juhud',
            'Amil-amil jazam dan pembagiannya (jazam 1 dan jazam 2)',
            'Lagu amil jazam',
            'Dalil amil jazam yang menjazamkan satu fi\'il mudhari\'',
            'Dalil amil jazam yang menjazamkan dua fi\'il mudhari\'',
            'Keterangan lam du\'a/lam amar',
            'Defenisi Fi\'il Amar',
            'Mabni fi\'il amar',
            'Dalil Mabninya fi\'il amar',
            'Lagu fi\'il amar',
            'Bentuk Mabni fi\'il amar',
            'Keterangan fi\'il mudhari\' dan fi\'il amar sambung dengan nun taukid dan nun jamak',
            'Dalil fi\'il mudhari\' dan fi\'il amar sambung dengan nun taukid dan nun jamak',
            'Wazan fi\'il amar tiga huruf/sulasi',
            'Wazan fi\'il amar empat huruf/ruba\'i',
            'Wazan fi\'il amar lima huruf/ khumasi',
            'Wazan fi\'il amar enam huruf/ sudasi',
            'Defenisi fi\'il lazim',
            'Lafaz-lafaz yang dipastikan lazim',
            'Dalil fi\'il lazim',
            'Ciri-ciri fi\'il lazim',
            'Defenisi fi\'il muta\'addi',
            'Pembagian fi\'il muta\'addi',
            'Ciri-ciri fi\'il muta\'addi',
            'Defenisi fi\'il ma\'lum',
            'Defenisi fi\'il majhul',
            'Ketentuan membaca fi\'il majhul',
            'Dalil fi\'il majhul',
            'Keterangan fi\'il majhul',
            'Wazan fi\'il madhi majhul',
            'Wazan fi\'il mudhari\' majhul',
            'Cara membuat fi\'il majhul dari bina ajwaf',
            'Defenisi fi\'il shohih',
            'Defenisi fi\'il mu\'tal',
            'Lagu huruf \'illat',
            'Pembagian/kelompok fi\'il shohih',
            'Pembagian/kelompok fi\'il mu\'tal',
            'Defenisi fi\'il bina mitsal dan contoh',
            'Keterangan fi\'il bina mitsal wawy',
            'Defenisi fi\'il bina ajwaf dan contoh',
            'Keterangan fi\'il bina ajwaf',
            'Defenisi fi\'il bina naqish dan contoh',
            'Keterangan fi\'il bina naqish',
            'Defenisi fi\'il bina lafif dan contoh',
        ];
        foreach ($itemsJ3 as $i => $nama) {
            $data[] = [
                'mapel_id' => 1,
                'kategori_id' => $k3,
                'nama' => $nama,
                'bobot' => 0,
                'skala_max' => 0,
                'input_type' => 'checkbox',
                'is_active' => 1,
            ];
        }

        // ===== KATEGORI 4 (urutan=4) =====
        $k4 = $kategoriMap[4] ?? null;
        $itemsJ4 = [
            'Isim-Isim yang Dibaca Rafa\'',
            'Dalil Isim yang Dibaca Rafa\'',
            'Lagu Isim yang Dibaca Rafa\'',
            'Defenisi Fa\'il',
            'Dalil Fa\'il',
            'Keterangan Fa\'il',
            'Pembagian Fa\'il',
            'Ciri-Ciri Fa\'il',
            'Defenisi Fail Isim Zhohir Beserta Contoh',
            'Defenisi Fa\'il Isim Dhomir Beserta Contoh',
            'Keterangan Fa\'il Isim Dhomir',
            'Defenisi Naibul Fa\'il',
            'Dalil Naibul Fa\'il',
            'Pembagian Naibul Fa\'il',
            'Keterangan Naibul Fa\'il',
            'Ciri-Ciri Mengetahui Naibul Fa\'il',
            'Defenisi Mubtada',
            'Qoidah Mubtada',
            'Dalil Mubtada',
            'Ciri-Ciri Menentukan Mubtada',
            'Qoidah Mubtada Dari Isim Nakirah',
            'Dalil Mubtada Dari Isim Nakirah',
            'Lagu Mubtada Boleh Nakirah',
            'Defenisi Khabar',
            'Dalil Khabar',
            'Ciri-Ciri Khabar',
            'Lagu Ciri Mubtada dan Khabar',
            'Pembagian Khabar',
            'Dalil Pembagian Khabar',
            'Defenisi Khabar Mufrad dan Ghairu Mufrad',
            'Dalil Khabar Mufrad',
            'Dalil Khabar Ghairu Mufrad',
            'Defenisi Khabar Ghairu Mufrad Berupa Jumlah Ismiyah',
            'Dalil Khabar Ghairu Mufrad Berupa Jumlah Ismiyah',
            'Defenisi Khabar Ghairu Mufrad Berupa Jumlah Fi\'liyah',
            'Dalil Khabar Ghairu Mufrad Berupa Jumlah Fi\'liyah',
            'Defenisi Khabar Ghairu Mufrad Berupa Zharaf',
            'Kalimat yang Biasa Menjadi Zharaf',
            'Dalil Khabar Ghairu Mufrad Berupa Zharaf',
            'Lagu Makna Zharaf',
            'Defenisi Khabar Ghairu Mufrad Berupa Jer-Majrur',
            'Dalil Khabar Ghairu Mufrad Berupa Jer-Majrur',
            'Keterangan Khabar Ghairu Mufrad Berupa Zharaf atau Jer-Majrur',
            'Dalil Khabar Ghairu Mufrad Berupa Zharaf atau Jer-Majrur',
            'Defenisi كان dan أنّ',
            'Qoidah Amil Nawasekh',
            'Amalan Amil Nawasekh',
            'Dalil Masing-Masing Amalan Amil Nawasekh',
            'Kelompok Amil Nawasekh',
            'Lagu Amil Nawasekh',
            'Keterangan Kelompok كان',
            'Keterangan Kelompok أنّ',
            'Defenisi Tabi\'',
            'Dalil Tabi\'',
            'Defenisi Naat dan Ciri-Cirinya',
            'Dalil Naat',
            'Pembagian Na\'at dan Defenisi Masing-Masing',
            'Qoidah Naat Hakiki',
            'Dalil Naat Hakiki',
            'Defenisi Na\'at Sababi dan Qaidahnya',
            'Dalil Na\'at Sababi',
            'Lagu Na\'at',
            'Defenisi Taukid',
            'Pembagian Taukid dan Defenisi Masing-Masing',
            'Dalil Taukid Lafdzi',
            'Dalil Taukid Maknawi',
            'Keterangan Taukid Maknawi',
            'Defenisi Athaf Nasaq dan Dalilnya',
            'Dalil Huruf Athaf',
            'Defenisi Badal',
            'Dalil Badal',
            'Ciri-Ciri Badal',
            'Isim-Isim yang Dibaca Nashab',
            'Lagu Isim-Isim yang Dibaca Nashab',
            'Defenisi Maf\'ul Bih',
            'Dalil Maf\'ul Bih',
            'Pembagian Maf\'ul Bih',
            'Keterangan Maf\'ul Bih',
            'Defenisi Maf\'ul Mutlaq dan Fungsinya',
            'Dalil Maf\'ul Mutlaq',
            'Defenisi Maf\'ul Lah',
            'Dalil Maf\'ul Lah',
            'Keterangan Maf\'ul Lah',
            'Defenisi Zharaf',
            'Dalil Zharaf',
            'Lafadz Yang Biasa Menjadi Zharaf dan Mudhaf',
            'Keterangan Lafadz yang Biasa Menjadi Zharaf dan Mudhaf',
            'Defenisi Maf\'ul Ma\'ah',
            'Dalil Maf\'ul Ma\'ah',
            'Perbedaan Waw Ma\'iyah dan Waw Athaf',
            'Defenisi Hal dan Dalilnya',
            'Qoidah Hal',
            'Defenisi Tamyiz dan Dalilnya',
            'Ciri-Ciri Tamyiz',
            'Defenisi Isimnya Laa dan Dalilnya',
            'Keterangan Isimnya Laa',
            'Lagu Isim Laa (Laa pada nakirah)',
            'Defenisi Istisna',
            'Adat-Adat Istisna',
            'Qaidah Bacaan Mustasnanya ألاّ',
            'Defenisi Tam Mujab, Tam Manfi, dan Kalam Naqis',
            'Dalil Istisna Kalam Tam Mujab dan Tam Manfi',
            'Dalil Kalam Naqish',
            'Lagu Mustasna ألاّ',
            'Defenisi Munada dan Pembagiannya',
            'Dalil Munada Mufrad',
            'Dalil Munada Mudhaf',
            'Isim yang Dibaca Jer dan Dalilnya',
        ];
        foreach ($itemsJ4 as $i => $nama) {
            $data[] = [
                'mapel_id' => 1,
                'kategori_id' => $k4,
                'nama' => $nama,
                'bobot' => 0,
                'skala_max' => 0,
                'input_type' => 'checkbox',
                'is_active' => 1,
            ];
        }

        if (!empty($data) && $k1 && $k2 && $k3 && $k4) {
            $this->db->table('kriteria_penilaian')->insertBatch($data);
        } elseif (empty($data)) {
            // sudah pernah di-seed, skip
        } else {
            echo "Error: Kategori Tasmi' tidak ditemukan\n";
        }
    }
}
